#!/bin/bash
# تعليمات بسيطة للتطبيق السريع
# Simple instructions for quick deployment

echo "======================================"
echo "تحديث SAP Integration - حذف التكرارات"
echo "======================================"
echo ""
echo "✅ تم إصلاح المشاكل التالية:"
echo "   1. إضافة صلاحيات الوصول"
echo "   2. إصلاح خطأ JSONB في استعلامات SQL"
echo ""
echo "📋 للتطبيق، اتبع الخطوات التالية:"
echo ""
echo "الطريقة 1 (سكريبت تلقائي):"
echo "   chmod +x update_module.sh"
echo "   ./update_module.sh"
echo ""
echo "الطريقة 2 (يدوياً):"
echo "   cd /home/lugalai/Lugal-ai"
echo "   ./venv/bin/python3 odoo-bin -c odoo_simple.conf -d lugal -u sap_integration --stop-after-init"
echo "   ./venv/bin/python3 odoo-bin -c odoo_simple.conf -d lugal"
echo ""
echo "📍 بعد التحديث، افتح:"
echo "   http://192.168.116.211:8069"
echo "   SAP Integration → Management Tools → حذف التكرارات"
echo ""
echo "📚 للمزيد من التفاصيل، راجع:"
echo "   - COMPLETE_FIX_SUMMARY_AR.md (ملخص كامل)"
echo "   - QUICK_FIX_AR.md (دليل سريع)"
echo ""
echo "======================================"

