[options]
addons_path = addons,odoo/addons
db_host = False
db_port = False
db_user = capo7amzah
db_password = False
db_name = lugal_local
http_port = 8071
data_dir = /home/capo7amzah/Documents/NBS-PROJECT/Lugal-ai/filestore_local
workers = 0
log_level = info
