[options]
addons_path = addons,odoo/addons
admin_passwd = admin
db_host = False
db_port = False
db_user = capo7amzah
db_password = False
db_name = lugal_local
http_port = 8070
logfile = odoo_local.log
log_level = info
workers = 0
dev_mode = reload
data_dir = ./filestore_local
