[options]
addons_path = .,addons,odoo\addons
; Force a default database so custom /api routes work without requiring db selection
db_name = lugal
db_host = localhost
db_port = 5432
db_user = odoo_user
db_password = root
http_port = 8070
; Single-db mode so requests can auto-select DB (monodb) and /api routes work without extra headers
dbfilter = ^lugal$
list_db = True
proxy_mode = True

