[options]
web.base.url = http://192.168.116.211:8069

addons_path = addons
db_host = localhost
db_port = 5432
db_user = odoo_user
db_password = root
admin_passwd = admin
dbfilter = ^lugal$
list_db = True
http_interface = 0.0.0.0
logfile = odoo.log
without_demo = True

# Debug mode settings
debug_mode = True
log_level = debug
log_handler = :DEBUG                     
xmlrpc_interface = 0.0.0.0
