# -*- coding: utf-8 -*-
from . import analytics_controller
from . import branch_controller
from . import bus_compat_controller
from . import call_controller
from . import channel_controller
from . import config_controller
from . import crm_notifications_controller
from . import customer_controller
from . import delivery_controller
from . import knowledge_controller
from . import pos_bridge_controller
from . import price_list_controller
from . import qa_controller
from . import supply_controller
from . import supply_chat_controller
from . import supply_stories_controller
from . import task_controller
from . import ticket_controller
from . import upload_controller
from . import user_controller
from . import workforce_controller
