# -*- coding: utf-8 -*-
from . import crm_attendance
from . import crm_audit_log
from . import crm_branch
from . import crm_call
from . import crm_call_queue
from . import crm_call_script
from . import crm_channel_config
from . import crm_channel_identity
from . import crm_customer
from . import crm_customer_stage
from . import crm_employee_kpi
from . import crm_interaction
from . import crm_kb_article
from . import crm_kb_notification
from . import crm_message_template
from . import crm_omnichannel_message
from . import crm_partner_extension
from . import crm_qa_review
from . import crm_requested_item
from . import crm_shift
from . import crm_supply_po
from . import crm_supply_po_line
from . import supply_workflow_config
from . import supply_workflow_approval_line
from . import supply_budget_allocation
from . import supply_inventory_minmax
from . import crm_supply_po_line_product
from . import crm_supply_po_extend
from . import crm_supply_po_chain_enhance
from . import lugal_supply_payment
from . import lugal_supply_payment_trace
from . import crm_supply_item_request_extend
from . import crm_supply_item_request_workflow
from . import crm_supply_negotiation_extend
from . import crm_supply_container_extend
from . import crm_supply_conversation
from . import crm_supply_message
from . import crm_supply_story
from . import crm_supply_typing
from . import crm_tag
from . import crm_task
from . import crm_ticket
